version: '3.9'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        image: nginx:1.23.1
        ports:
            - "80:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/html
            - ./public:/var/www/html/public:ro
            - ./storage/app:/var/www/html/storage/app:ro
        container_name: blog_nginx
        restart: unless-stopped

    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            -  ./:/var/www/html
        links:
            - postgres
        container_name: blog_fpm
        restart: unless-stopped

    postgres:
        image: postgres:12.12
        ports:
            - '5432:5432'
        user: postgres
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=blog
        container_name: blog_postgres
        restart: unless-stopped

    npm:
        image: node:14
        working_dir: /var/www/html
        entrypoint: [ "npm" ]
        volumes:
            - ./:/var/www/html
